### ISSUE TITLE
[1.15.2][Forge] not regenerating on death.

### ISSUE THREAD

**Issue by Bass2style** [kwpugh/OverpoweredPickles#1]
when you die, "definitive hearts" are not regenerating, you have the 10 vanilla hearts that are full, but the Pickels hearts are empty, and eating doesn't regen it. (giving a regen effect doesn't work either.)
the only way to get those hearts back, is to eat a new Insane Pickels. (or the tier that you want.)

when you take damage, but you don't die, you can regen without problem.

i dont know if it's correclty explained, but here is a vidéo, it's more understandable i think : https://www.youtube.com/watch?v=YvxgLPufIXw (yt is treating it, so idk when it should be online)

**Comment by kwpugh** [comment]
That would be correct. The extra hearts do not survive  player death.

I may look at adding that in the future.

**Comment by Bass2style** [comment]
okay, so it's an intended feature.

it's possible to, if "do not keep hearts" is enabled, to remove those "empty" hearts, because it's disturbing to see hearts that you can't regen. XD

**Comment by kwpugh** [comment]
As a work-around, you can eat a Cleansing Pickle to remove the empty hearts.

**Comment by kwpugh** [comment]
Seems to have disappeared in 1.16.5 and 1.17.1

1.15.2 is no longer supported.
